# Generated by Django 4.1.5 on 2023-01-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Aктер и режиссер', 'verbose_name_plural': 'Aктеры и режиссеры'},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
